# -*- coding: utf-8 -*-
"""Ai Text to Imageipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16FuDY86jgJw6Oh61R2ilnRcm6xTdc4Ja

AI Text-to-Image Generator Project

Title: AI Text-to-Image Generator with Stable Diffusion

Objective: Create a web-based application that converts text prompts into high-quality images using AI models like Stable Diffusion.

Key Features:

User-friendly prompt input
GPU-accelerated image generation
Secure model loading with safetensors
Image display and saving
Technology Stack: Python, Hugging Face diffusers, PyTorch, Matplotlib

Step 1: Setup Environment
Install required packages:
"""

!pip install diffusers transformers accelerate --upgrade

!pip install safetensors

"""Step 2: Import libraries:"""

import torch
from diffusers import StableDiffusionPipeline
import matplotlib.pyplot as plt

"""Step 3: Hugging Face Authentication

Obtain your Hugging Face API token
Authenticate:
"""

from huggingface_hub import login
login("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")

"""Step 3: Load Stable Diffusion Model"""

pipe=StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
     torch_dtype=torch.float16,
    use_safetensors=True
)
pipe=pipe.to("cuda")

"""Step 5: Generate Images

Take user input:

Workflow Diagram
Input → User provides text prompt
Processing → Stable Diffusion generates image
Output → Display + Save image
"""

user_prompt= input("Enter Your image Prompt:")

"""Generate and display:"""

image= pipe(user_prompt).images[0]
#Disply the generated image
plt.imshow(image)
plt.axis("off")
plt.title("Generated Image")
plt.show()